### ISSUE TITLE
how to run it ?

### ISSUE THREAD

**Issue by kakamband** [suconghou/u2worker#1]
hi suconghou,
how to run it ?
im make worker on cloudflare & paste all text value of index.js (first realease)
but not work after deploy
please help me , if it's possible make video tutorial for personal usage.
waiting for your response
finest regards

**Comment by suconghou** [comment]
@kakamband  you should use latest release, I have updated readme

**Comment by kakamband** [comment]
after going all your steps exactly , getting error in player :
AbortError: The operation was aborted.
 播放出错,请刷新重试

**Comment by suconghou** [comment]
did you see `Chrome DevTools` network & console panel , what's happening;  can https://video.feds.club/ works ok without your worker ?

**Comment by kakamband** [comment]
hello again suconghou,
all your steps are corectly & work well for me after repeat all the steps
but very very important feture for me is embed link from video.fed.club players to use out side , simple linke im my website posts or etc.
if it's possible make embed button for https://video.feds.club/ players.
waiting for your response
finest regards

**Comment by suconghou** [comment]
@kakamband  It already has the button on the player page , see https://github.com/suconghou/u2web#embed-video for detail
